// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwGI7Sib1OE4T0ooQIhzkWQVxmrg36tNk',
    appId: '1:316219372562:web:48c88270b5c9f2b27214cb',
    messagingSenderId: '316219372562',
    projectId: 'elag-demo',
    authDomain: 'elag-demo.firebaseapp.com',
    storageBucket: 'elag-demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBflQhn3btWU93SXN0eR4gQkpoSZVxhwAo',
    appId: '1:316219372562:android:12845e2c611bbc3f7214cb',
    messagingSenderId: '316219372562',
    projectId: 'elag-demo',
    storageBucket: 'elag-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwCoAwpUT2tWq8nHyPsGKlX53AnssC4IQ',
    appId: '1:316219372562:ios:a8da64677bc2b1367214cb',
    messagingSenderId: '316219372562',
    projectId: 'elag-demo',
    storageBucket: 'elag-demo.appspot.com',
    iosBundleId: 'com.example.elag',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwCoAwpUT2tWq8nHyPsGKlX53AnssC4IQ',
    appId: '1:316219372562:ios:72299b4c7ded8e497214cb',
    messagingSenderId: '316219372562',
    projectId: 'elag-demo',
    storageBucket: 'elag-demo.appspot.com',
    iosBundleId: 'com.example.elag.RunnerTests',
  );
}
